### ISSUE TITLE
When ending a session, user asked to confirm twice

### ISSUE THREAD

**Issue by alymurray** [UPchieve/server#36] opened 2018-09-05 15:15 UTC
For student users, they have to click OK twice before the prompt will go away and they are redirected to feedback. They should only have to click once. I have not checked on volunteer users.

**Comment by jmromer** [comment] 2019-03-26 01:57
@alymurray Are you still seeing this? I can't reproduce it—possibly fixed by changes since this was opened.

Steps I'm using to attempt a reproduction (in FF and Chrome on a Mac):

1. Login as a student,
2. Start a new coaching session (Math > Calculus)
3. Once in the session room, click "End Session"
4. In the alert box that opens, click "OK" (only once is necessary)
5. Observe the redirect to the dashboard

**Closed** 2019-03-29 12:34 UTC
Labels: bug
